version: '3.8'
services:
  backend:
    build: ./zaapsign_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=zaapsign_db
      - DB_USER=admin
      - DB_PASSWORD=admin

  frontend:
    build: ./zaapsign_frontend
    ports:
      - "3000:4200"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zaapsign_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
